#!/usr/bin/env python3

import os, sys

sys_args = sys.argv

colored = '--colored' in sys_args or '-c' in sys_args
class_ = '--class' in sys_args or '-cl' in sys_args

file_name = None

for arg in sys_args[1:]:
    if '-' not in arg:
        file_name = arg

        break

if file_name is None:
    print('No file name provided')

    exit(1)

if not file_name.endswith('.py'):
    file_name += '.py'

if os.path.exists(file_name):
    print('File already exists')

    exit(1)

org_class_name = file_name.replace('.py', '')
org_class_comps = org_class_name.split('_')

class_name = ''

for org_class_comp in org_class_comps:
    class_name += org_class_comp.lower().title()

content = ''

if colored:
    content += '# region [ rgba(0, 0, 0, 0.15) ]\n'

content += '''# ---------------------------------------------------------------- Imports --------------------------------------------------------------- #

# System


# Pip


# Local

'''

if colored:
    content += '\n# endregion\n\n\n# region [ rgba(0, 0, 0, 0.2) ]'

if class_:
    content += '''
# ----------------------------------------------------------------- Class ---------------------------------------------------------------- #

class ''' + class_name + ''':
    # ------------------------------------------------------------- Init ------------------------------------------------------------- #
    def __init__(
        self
    ):
        return


    # ------------------------------------------------------- Public properties ------------------------------------------------------ #


    # --------------------------------------------------------- Public methods ------------------------------------------------------- #


    # ------------------------------------------------------- Private properties ----------------------------------------------------- #


    # --------------------------------------------------------- Private methods ------------------------------------------------------ #


'''
else:
    content += '''
# ----------------------------------------------------------- Public properties ---------------------------------------------------------- #


# ------------------------------------------------------------- Public methods ----------------------------------------------------------- #


# ----------------------------------------------------------- Private properties --------------------------------------------------------- #


# ------------------------------------------------------------- Private methods ---------------------------------------------------------- #


'''

if colored:
    content  += '# endregion'

with open(file_name, 'w') as f:
    f.write(content)